How to install and use git hooks
================================

= Hooks used in the project
Project's repository uses following client-side hooks:

[[pre-push]]
Pre-push::
    Pre-push hook is used to ensure that code being published in repository is of good quality. For quality checks performed, see https://github.com/E-bank-Dream-team/openapi-rest-archetype/wiki/Static-analysis#quality-checks[Quality checks]. Due to performing extensive actions, push may take some time. +
    Pre-push hook uses Maven `static-analysis` profile which adds tools configuration and executes tools (also generating reports) during `test` phase. You may run `mvn -P static-analysis clean test` manually to see if your code will pass quality checks before pushing it to repository (so you have a chance to fix issues).

TIP: To investigate why push didn't happen, use `git push` command from terminal instead of using git client built into IDE. You may also try to find tools' reports (should be under `target/site` directory).

= Hooks installation

To install the hooks, run appropriate scripts from *project's base directory* as described below. You _may_ need to make script executable first.

Hooks need to be installed manually on each developer's machine.

== Windows batch script

Pre-push::
    Run `resources\git\scripts\pre-push-install.cmd`

== Linux shell (Git Bash)

Pre-push::
    Run `./resources/git/scripts/pre-push-install.sh`
