package com.example.controllers;

import com.example.autogenerated.api.DateTimeApi;
import com.example.autogenerated.dto.DateAndTimeDto;
import com.example.services.DateTimeService;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.annotations.Api;

@Api(tags = "date-time")
@RestController
public class DateTimeController implements DateTimeApi {

	private final DateTimeService dateTimeService;

	public DateTimeController(DateTimeService dateTimeService) {
		this.dateTimeService = dateTimeService;
	}

	@Override
	public ResponseEntity<DateAndTimeDto> getDateTime() {
		DateAndTimeDto dateAndTimeDto = new DateAndTimeDto();
		dateAndTimeDto.setDateTime(dateTimeService.getCurrentDateAndTime());
		return ResponseEntity.ok(dateAndTimeDto);
	}
}
